---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  console:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: bash
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    volumes:
      - .:/work
    working_dir: /work

  robctl:
    image: ruby:2.4
    depends_on:
      - kafka
    command: bin/robctl
    environment:
      KAFKA_BROKER: kafka:9092
    volumes:
      - .:/work
      - ruby-2.4-bundle:/usr/local/bundle
    working_dir: /work

volumes:
  ruby-2.4-bundle: {}
