#! /bin/bash -eu

create-topic() {
  /usr/bin/kafka-topics --zookeeper $KAFKA_ZOOKEEPER_CONNECT --create --if-not-exists --replication-factor 1 --partitions 1 --topic $1 
}

create-topic robot-commands 
create-topic robot-states
